source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'SmartForecast' do
  use_frameworks!

  pod 'Alamofire', '~> 4.7'

  pod 'SwiftyJSON', '~> 4.0'

  target 'SmartForecastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartForecastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
